/* AUTO-GENERATED + LLM 분류 보정 */
window.AD_DATA = {
  "meta": {
    "lastUpdated": "2026-06-11 09:00",
    "nextUpdate": "(주 1회 자동)",
    "weekLabel": "2026-06-11",
    "owner": "네이버웹툰",
    "competitors": [
      "리디",
      "카카오페이지"
    ],
    "sources": {
      "meta": {
        "label": "Meta (페북·인스타)",
        "confidence": "정확",
        "note": "Ad Library 실수집"
      },
      "google": {
        "label": "Google",
        "confidence": "추정",
        "note": "Transparency Center (수집 예정)"
      },
      "tiktok": {
        "label": "TikTok",
        "confidence": "추정",
        "note": "Creative Center (수집 예정)"
      },
      "kakao": {
        "label": "Kakao",
        "confidence": "수동",
        "note": "공식 라이브러리 없음"
      }
    },
    "dataMode": "real",
    "collectorNote": "Meta 실데이터 자동 수집 · 작품명·성향·장르는 LLM 정밀 분류(정확) + 휴리스틱(추정) 혼합."
  },
  "weeklyTrend": [
    {
      "week": "06-11",
      "네이버웹툰": 10,
      "카카오페이지": 50,
      "리디": 53
    }
  ],
  "dateRange": {
    "min": "2026-04-20",
    "max": "2026-06-11"
  },
  "creatives": [
    {
      "id": "meta_2661151740949738",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "브랜드·뉴스 광고",
      "gender": "all",
      "genre": "브랜드·뉴스",
      "title_conf": "추정",
      "ad_kind": "브랜드·뉴스",
      "type": "image",
      "image": "assets/meta_2661151740949738.jpg",
      "copy": "_ ✓아이브 日 오리콘•빌보드 차트 최정상 ✓서울 - 도쿄 - 타이페이 - 상하이! 규현, 데뷔 20주년 기념 단독 팬미팅 진행 ✓드래곤포니, 6월 10일 일본 데뷔! 도쿄-오사카 단독 투어 개최 ✓‘괴담에 떨어져도 출근을 해야 하는구나’ 웹툰 공개와",
      "advertiser": "kakao.entertainment",
      "libId": "2661151740949738",
      "first_seen": "2026-06-07",
      "last_seen": "2026-06-11",
      "duration_days": 5,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_2163806437495651",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "괴담에 떨어져도 출근을 해야 하는구나",
      "gender": "all",
      "genre": "드라마",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_2163806437495651.jpg",
      "copy": "🎊원작 3.7억뷰 #괴담출근 웹툰 론칭🎊 비운의 현장탐사팀 D조에 배정된 김솔음, 그리고 전원 사망 위기에 처한 D조의 운명은? #괴담에떨어져도출근을해야하는구나 #카카오페이지 #kakaopage 0:00 / 0:59 HTTPS://PAGE.KAKAO.",
      "advertiser": "kakaopage",
      "libId": "2163806437495651",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1563547078662312",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "열혈강호",
      "gender": "male",
      "genre": "무협",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1563547078662312.jpg",
      "copy": "100화 이상? 오히려 좋아💥 무협은 몰아봐야 제맛이지! 끊김 없는 무협 감상, #카카오페이지 에서! 🏃 #kakaopage LINK-PAGE.KAKAO.COM 열혈강호 오리지널 독점 웹툰, 웹소설 부터 책 까지 한 곳에서 즐기세요. 인기 콘텐츠가 기",
      "advertiser": "kakaopage",
      "libId": "1563547078662312",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1492679269002693",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "은동스",
      "gender": "all",
      "genre": "일상",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1492679269002693.jpg",
      "copy": "Q: 최애 입덕 계기가 뭐야? A: #카카오페이지 접속...💖 #kakaopage LINK-PAGE.KAKAO.COM 은동스+옹동스 오리지널 독점 웹툰, 웹소설 부터 책 까지 한 곳에서 즐기세요. 인기 콘텐츠가 기다리면 무료! Learn More",
      "advertiser": "kakaopage",
      "libId": "1492679269002693",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1087482327272671",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "괴담에 떨어져도 출근을 해야 하는구나",
      "gender": "all",
      "genre": "드라마",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1087482327272671.jpg",
      "copy": "🎊원작 3.7억뷰 #괴담출근 웹툰 론칭🎊 대한쫄보협회 회장급인데 괴담 회사에 꾸역꾸역 출근하는 이유 #괴담에떨어져도출근을해야하는구나 #카카오페이지 #kakaopage",
      "advertiser": "kakaopage",
      "libId": "1087482327272671",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_2413734255785665",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "금지소년",
      "gender": "male",
      "genre": "액션",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_2413734255785665.jpg",
      "copy": "🚨SSS급 세계관 최강자 정모🚨 #카카오페이지 로 먼치킨 전원 집합! #kakaopage LINK-PAGE.KAKAO.COM 금지소년 오리지널 독점 웹툰, 웹소설 부터 책 까지 한 곳에서 즐기세요. 인기 콘텐츠가 기다리면 무료! Learn More",
      "advertiser": "kakaopage",
      "libId": "2413734255785665",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1007404291998251",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "벨제바브",
      "gender": "male",
      "genre": "액션",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1007404291998251.jpg",
      "copy": "도파민 풀 충전 완료!🔋 속 시원한 사이다 액션 웹툰, 지금 #카카오페이지 에서▶️ #kakaopage LINK-PAGE.KAKAO.COM 벨제바브 [단행본] 오리지널 독점 웹툰, 웹소설 부터 책 까지 한 곳에서 즐기세요. 인기 콘텐츠가 기다리면 무료",
      "advertiser": "kakaopage",
      "libId": "1007404291998251",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1572373328235893",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "괴담에 떨어져도 출근을 해야 하는구나",
      "gender": "all",
      "genre": "드라마",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1572373328235893.jpg",
      "copy": "🎊원작 3.7억뷰 #괴담출근 웹툰 론칭🎊 비운의 현장탐사팀 D조에 배정된 김솔음, 그리고 전원 사망 위기에 처한 D조의 운명은? #괴담에떨어져도출근을해야하는구나 #카카오페이지 #kakaopage 0:00 / 0:59 HTTPS://PAGE.KAKAO.",
      "advertiser": "kakaopage",
      "libId": "1572373328235893",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1906819266693231",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "신의 선물",
      "gender": "female",
      "genre": "로판",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1906819266693231.jpg",
      "copy": "🪧[퀘스트가 도착했습니다] 지금 #카카오페이지 에서, 당신만의 로판 남주를 골라주세요! 💖 #kakaopage LINK-PAGE.KAKAO.COM 신의 선물 [고화질, 완결] 오리지널 독점 웹툰, 웹소설 부터 책 까지 한 곳에서 즐기세요. 인기 콘텐츠",
      "advertiser": "kakaopage",
      "libId": "1906819266693231",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1350284223678924",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "불멸자",
      "gender": "male",
      "genre": "판타지",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1350284223678924.jpg",
      "copy": ">>나도 모르게 과몰입 하게 돼<< 직업별 몰입도 1️⃣0️⃣0️⃣% 현판 웹소 준비 완료! 지금 #카카오페이지 에서▶️ #kakaopage LINK-PAGE.KAKAO.COM 불멸자 오리지널 독점 웹툰, 웹소설 부터 책 까지 한 곳에서 즐기세요. 인",
      "advertiser": "kakaopage",
      "libId": "1350284223678924",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1038084581981396",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "검은 머리 미군 대원수",
      "gender": "male",
      "genre": "판타지",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1038084581981396.jpg",
      "copy": "미국 군대에서 1짱 먹은 동양인의 비밀은...? 대체역사물 압도적 1황🏆 #검은머리미군대원수 #카카오페이지 #kakaopage 0:00 / 0:41 HTTPS://PAGE.KAKAO.COM/ 지금 카카오페이지에서 Learn More",
      "advertiser": "kakaopage",
      "libId": "1038084581981396",
      "first_seen": "2026-06-09",
      "last_seen": "2026-06-11",
      "duration_days": 3,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_930756466636294",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "괴담에 떨어져도 출근을 해야 하는구나",
      "gender": "all",
      "genre": "드라마",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_930756466636294.jpg",
      "copy": "🎊원작 3.7억뷰 #괴담출근 웹툰 론칭🎊 백일몽 주식회사 엘리트 신입사원 김솔음의 입사 첫날 따끈 후기 #괴담에떨어져도출근을해야하는구나 #카카오페이지 #kakaopage HTTPS://PAGE.KAKAO.COM/ Learn More HTTPS://PA",
      "advertiser": "kakaopage",
      "libId": "930756466636294",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1483136259794631",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "네가 있던 미래에선",
      "gender": "female",
      "genre": "로판",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1483136259794631.jpg",
      "copy": "🪧[퀘스트가 도착했습니다] 지금 #카카오페이지 에서, 당신만의 로판 남주를 골라주세요! 💖 #kakaopage LINK-PAGE.KAKAO.COM 네가 있던 미래에선 오리지널 독점 웹툰, 웹소설 부터 책 까지 한 곳에서 즐기세요. 인기 콘텐츠가 기다리",
      "advertiser": "kakaopage",
      "libId": "1483136259794631",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1880610345947291",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "프리징",
      "gender": "male",
      "genre": "액션",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1880610345947291.jpg",
      "copy": "🚨SSS급 세계관 최강자 정모🚨 #카카오페이지 로 먼치킨 전원 집합! #kakaopage LINK-PAGE.KAKAO.COM 프리징 완전판 오리지널 독점 웹툰, 웹소설 부터 책 까지 한 곳에서 즐기세요. 인기 콘텐츠가 기다리면 무료! Learn Mor",
      "advertiser": "kakaopage",
      "libId": "1880610345947291",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1366145932242045",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "검명무명",
      "gender": "male",
      "genre": "무협",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1366145932242045.jpg",
      "copy": "⚠️주의⚠️ 정주행 하느라 시간 감각이 없어집니다! #카카오페이지 #kakaopage LINK-PAGE.KAKAO.COM 검명무명 오리지널 독점 웹툰, 웹소설 부터 책 까지 한 곳에서 즐기세요. 인기 콘텐츠가 기다리면 무료! Learn More",
      "advertiser": "kakaopage",
      "libId": "1366145932242045",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_990745220419874",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "천생연분",
      "gender": "all",
      "genre": "로맨스",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_990745220419874.jpg",
      "copy": "널 위해 준비했어...💖 가슴이 웅장해지는 억대 조회수 웹툰, 지금 #카카오페이지 에서▶️ #kakaopage LINK-PAGE.KAKAO.COM 천생연분 오리지널 독점 웹툰, 웹소설 부터 책 까지 한 곳에서 즐기세요. 인기 콘텐츠가 기다리면 무료! ",
      "advertiser": "kakaopage",
      "libId": "990745220419874",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_26617379547940623",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "괴담에 떨어져도 출근을 해야 하는구나",
      "gender": "all",
      "genre": "드라마",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_26617379547940623.jpg",
      "copy": "🎊원작 3.7억뷰 #괴담출근 웹툰 론칭🎊 비운의 현장탐사팀 D조에 배정된 김솔음, 그리고 전원 사망 위기에 처한 D조의 운명은? #괴담에떨어져도출근을해야하는구나 #카카오페이지 #kakaopage 0:00 / 0:59 HTTPS://PAGE.KAKAO.",
      "advertiser": "kakaopage",
      "libId": "26617379547940623",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_2068201840786061",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "(로판 추천)",
      "gender": "female",
      "genre": "로판",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_2068201840786061.jpg",
      "copy": "로판 권태기에는 더 큰 자극으로! #카카오페이지 가 고자극 웹소 엄선해왔어🍽️ #kakaopage LINK-PAGE.KAKAO.COM kakaopage 오리지널 독점 웹툰, 웹소설 부터 책 까지 한 곳에서 즐기세요. 인기 콘텐츠가 기다리면 무료! Le",
      "advertiser": "kakaopage",
      "libId": "2068201840786061",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1547473463634405",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "열혈강호",
      "gender": "male",
      "genre": "무협",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1547473463634405.jpg",
      "copy": "100화 이상? 오히려 좋아💥 무협은 몰아봐야 제맛이지! 끊김 없는 무협 감상, #카카오페이지 에서! 🏃 #kakaopage FB.COM 지금 카카오페이지에서 자세히 보기",
      "advertiser": "kakaopage",
      "libId": "1547473463634405",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1003615952528075",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "괴담에 떨어져도 출근을 해야 하는구나",
      "gender": "all",
      "genre": "드라마",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1003615952528075.jpg",
      "copy": "🎊원작 3.7억뷰 #괴담출근 웹툰 론칭🎊 괴담 회사에 엘리트 신입 등장!? #괴담에떨어져도출근을해야하는구나 #카카오페이지 #kakaopage HTTPS://PAGE.KAKAO.COM/ Learn More HTTPS://PAGE.KAKAO.COM/ Le",
      "advertiser": "kakaopage",
      "libId": "1003615952528075",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_2087155228678772",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "망나니 PD 아이돌로 살아남기",
      "gender": "all",
      "genre": "드라마",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_2087155228678772.jpg",
      "copy": "음방 대기실에서 벌어지는 핑크빛 친목...?!🫣💥 #망나니PD아이돌로살아남기 #카카오페이지 #kakaopage HTTPS://PAGE.KAKAO.COM/ See Details HTTPS://PAGE.KAKAO.COM/ See Details HTTPS:",
      "advertiser": "kakaopage",
      "libId": "2087155228678772",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_4809177229340094",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "잊혀진 들판",
      "gender": "female",
      "genre": "로맨스",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_4809177229340094.jpg",
      "copy": "망한 짝사랑? 혐관? 맛이 없을 수가 없다!😋 김수지 작가 x 스푼 작가 역대급 로맨스 신작! 지금 #카카오페이지 에서❤️‍🔥 #잊혀진들판 #kakaopage HTTPS://PAGE.KAKAO.COM/ See Details HTTPS://PAGE.KA",
      "advertiser": "kakaopage",
      "libId": "4809177229340094",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_994838813468971",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "금지소년",
      "gender": "male",
      "genre": "액션",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_994838813468971.jpg",
      "copy": "🚨SSS급 세계관 최강자 정모🚨 #카카오페이지 로 먼치킨 전원 집합! #kakaopage FB.COM 지금 카카오페이지에서 자세히 보기",
      "advertiser": "kakaopage",
      "libId": "994838813468971",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_866863235880467",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "괴담에 떨어져도 출근을 해야 하는구나",
      "gender": "all",
      "genre": "드라마",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_866863235880467.jpg",
      "copy": "🎊원작 3.7억뷰 #괴담출근 웹툰 론칭🎊 괴담 회사에 엘리트 신입 등장!? #괴담에떨어져도출근을해야하는구나 #카카오페이지 #kakaopage HTTPS://PAGE.KAKAO.COM/ Learn More HTTPS://PAGE.KAKAO.COM/ Le",
      "advertiser": "kakaopage",
      "libId": "866863235880467",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1867737587231878",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "천재 대장장이의 게임",
      "gender": "male",
      "genre": "판타지",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1867737587231878.jpg",
      "copy": "레벨 1 무직이 손재주만 레벨 353까지 찍었을 때 벌어지는 일 #천재대장장이의게임 #카카오페이지 #kakaopage HTTPS://PAGE.KAKAO.COM/ 지금 카카오페이지에서 자세히 보기",
      "advertiser": "kakaopage",
      "libId": "1867737587231878",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1802487394201355",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "괴담에 떨어져도 출근을 해야 하는구나",
      "gender": "all",
      "genre": "드라마",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1802487394201355.jpg",
      "copy": "🎊원작 3.7억뷰 #괴담출근 웹툰 론칭🎊 비운의 현장탐사팀 D조에 배정된 김솔음, 그리고 전원 사망 위기에 처한 D조의 운명은? #괴담에떨어져도출근을해야하는구나 #카카오페이지 #kakaopage 0:00 / 0:59 HTTPS://PAGE.KAKAO.",
      "advertiser": "kakaopage",
      "libId": "1802487394201355",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_977501801734864",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "괴담에 떨어져도 출근을 해야 하는구나",
      "gender": "all",
      "genre": "드라마",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_977501801734864.jpg",
      "copy": "🎊원작 3.7억뷰 #괴담출근 웹툰 론칭🎊 모두가 기다린 입사동기즈 첫 만남 에피소드를 웹툰으로! #괴담에떨어져도출근을해야하는구나 #카카오페이지 #kakaopage HTTPS://PAGE.KAKAO.COM/ Learn More HTTPS://PAGE.K",
      "advertiser": "kakaopage",
      "libId": "977501801734864",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_2031042247797565",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "괴담에 떨어져도 출근을 해야 하는구나",
      "gender": "all",
      "genre": "드라마",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_2031042247797565.jpg",
      "copy": "🎊원작 3.7억뷰 #괴담출근 웹툰 론칭🎊 괴담 회사에 엘리트 신입 등장!? #괴담에떨어져도출근을해야하는구나 #카카오페이지 #kakaopage HTTPS://PAGE.KAKAO.COM/ Learn More HTTPS://PAGE.KAKAO.COM/ Le",
      "advertiser": "kakaopage",
      "libId": "2031042247797565",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1671719480545445",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "(미상)",
      "gender": "male",
      "genre": "액션",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1671719480545445.jpg",
      "copy": "🚨SSS급 세계관 최강자 정모🚨 #카카오페이지 로 먼치킨 전원 집합! #kakaopage 0:00 / 0:53",
      "advertiser": "kakaopage",
      "libId": "1671719480545445",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_964192093106737",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "괴담에 떨어져도 출근을 해야 하는구나",
      "gender": "all",
      "genre": "드라마",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_964192093106737.jpg",
      "copy": "🎊원작 3.7억뷰 #괴담출근 웹툰 론칭🎊 모두가 기다린 입사동기즈 첫 만남 에피소드를 웹툰으로! #괴담에떨어져도출근을해야하는구나 #카카오페이지 #kakaopage HTTPS://PAGE.KAKAO.COM/ Learn More HTTPS://PAGE.K",
      "advertiser": "kakaopage",
      "libId": "964192093106737",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_861797873171591",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "잊혀진 들판",
      "gender": "female",
      "genre": "로맨스",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_861797873171591.jpg",
      "copy": "역대급 미모 + 짝사랑 인데 남주랑 혐관이라니!😭 #잊혀진들판 #카카오페이지 #kakaopage HTTPS://PAGE.KAKAO.COM/ See Details HTTPS://PAGE.KAKAO.COM/ See Details HTTPS://PAGE.K",
      "advertiser": "kakaopage",
      "libId": "861797873171591",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1685419446124797",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "잊혀진 들판",
      "gender": "female",
      "genre": "로맨스",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1685419446124797.jpg",
      "copy": "친엄마가 딸한테 이래도 되는 건가요..?! 😱 #잊혀진들판 #카카오페이지 #kakaopage HTTPS://PAGE.KAKAO.COM/ See Details HTTPS://PAGE.KAKAO.COM/ See Details HTTPS://PAGE.KAK",
      "advertiser": "kakaopage",
      "libId": "1685419446124797",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1311845503879488",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "잊혀진 들판",
      "gender": "female",
      "genre": "로맨스",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1311845503879488.jpg",
      "copy": "살아남기 위해선 어쩔 수 없던 그녀의 선택?!💥 #잊혀진들판 #카카오페이지 #kakaopage #잊혀진들판 #kakaopage 0:00 / 0:51 HTTPS://PAGE.KAKAO.COM/ 지금 카카오페이지에서 See Details",
      "advertiser": "kakaopage",
      "libId": "1311845503879488",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_998000049759698",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "벨제바브",
      "gender": "male",
      "genre": "액션",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_998000049759698.jpg",
      "copy": "도파민 풀 충전 완료!🔋 속 시원한 사이다 액션 웹툰, 지금 #카카오페이지 에서▶️ #kakaopage 0:00 / 1:00",
      "advertiser": "kakaopage",
      "libId": "998000049759698",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1307983954261816",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "괴담에 떨어져도 출근을 해야 하는구나",
      "gender": "all",
      "genre": "드라마",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1307983954261816.jpg",
      "copy": "🎊원작 3.7억뷰 #괴담출근 웹툰 론칭🎊 모두가 기다린 입사동기즈 첫 만남 에피소드를 웹툰으로! #괴담에떨어져도출근을해야하는구나 #카카오페이지 #kakaopage HTTPS://PAGE.KAKAO.COM/ Learn More HTTPS://PAGE.K",
      "advertiser": "kakaopage",
      "libId": "1307983954261816",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1317778273169975",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "천재 대장장이의 게임",
      "gender": "male",
      "genre": "판타지",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1317778273169975.jpg",
      "copy": "Lv.1👶🏻과 전설 클래스✨가 동일 인물이라고? #천재대장장이의게임 보러 가기 🏹▶️ #카카오페이지 #kakaopage HTTPS://PAGE.KAKAO.COM/ 지금 카카오페이지에서 자세히 보기",
      "advertiser": "kakaopage",
      "libId": "1317778273169975",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1012271794973163",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "열혈강호",
      "gender": "male",
      "genre": "무협",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1012271794973163.jpg",
      "copy": "100화 이상? 오히려 좋아💥 무협은 몰아봐야 제맛이지! 끊김 없는 무협 감상, #카카오페이지 에서! 🏃 #kakaopage 0:00 / 0:59 FB.COM 지금 카카오페이지에서 자세히 보기",
      "advertiser": "kakaopage",
      "libId": "1012271794973163",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1270436038227614",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "벨제바브",
      "gender": "male",
      "genre": "액션",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1270436038227614.jpg",
      "copy": "도파민 풀 충전 완료!🔋 속 시원한 사이다 액션 웹툰, 지금 #카카오페이지 에서▶️ #kakaopage FB.COM 지금 카카오페이지에서 자세히 보기",
      "advertiser": "kakaopage",
      "libId": "1270436038227614",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1519031426595594",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "망나니 PD 아이돌로 살아남기",
      "gender": "all",
      "genre": "드라마",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1519031426595594.jpg",
      "copy": "내가 이걸 믿어야 해, 말아야 해...🫠 #망나니PD아이돌로살아남기 #카카오페이지 #kakaopage 0:00 / 0:40 HTTPS://PAGE.KAKAO.COM/ 지금 카카오페이지에서 Learn More",
      "advertiser": "kakaopage",
      "libId": "1519031426595594",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1162081469442114",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "괴담에 떨어져도 출근을 해야 하는구나",
      "gender": "all",
      "genre": "드라마",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1162081469442114.jpg",
      "copy": "🎊원작 3.7억뷰 #괴담출근 웹툰 론칭🎊 괴담 회사에 엘리트 신입 등장!? #괴담에떨어져도출근을해야하는구나 #카카오페이지 #kakaopage HTTPS://PAGE.KAKAO.COM/ Learn More HTTPS://PAGE.KAKAO.COM/ Le",
      "advertiser": "kakaopage",
      "libId": "1162081469442114",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_977867501710158",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "괴담에 떨어져도 출근을 해야 하는구나",
      "gender": "all",
      "genre": "드라마",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_977867501710158.jpg",
      "copy": "🎊원작 3.7억뷰 #괴담출근 웹툰 론칭🎊 대한쫄보협회 회장급인데 괴담 회사에 꾸역꾸역 출근하는 이유 #괴담에떨어져도출근을해야하는구나 #카카오페이지 #kakaopage",
      "advertiser": "kakaopage",
      "libId": "977867501710158",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_2248242375982087",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "잊혀진 들판",
      "gender": "female",
      "genre": "로맨스",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_2248242375982087.jpg",
      "copy": "벽 뒤는 로맨스 클리셰입니다만...( ͡~ ͜ʖ ͡°) 역대급 쌍방 구원서사 로맨스 신작! 지금 #카카오페이지 에서❤️‍🔥 #잊혀진들판 #kakaopage HTTPS://PAGE.KAKAO.COM/ See Details HTTPS://PAGE.KAKA",
      "advertiser": "kakaopage",
      "libId": "2248242375982087",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1004219169209346",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "잊혀진 들판",
      "gender": "female",
      "genre": "로맨스",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1004219169209346.jpg",
      "copy": "벽 뒤는 로맨스 클리셰입니다만...( ͡~ ͜ʖ ͡°) 역대급 쌍방 구원서사 로맨스 신작! 지금 #카카오페이지 에서❤️‍🔥 #잊혀진들판 #kakaopage HTTPS://PAGE.KAKAO.COM/ See Details HTTPS://PAGE.KAKA",
      "advertiser": "kakaopage",
      "libId": "1004219169209346",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1328105622210872",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "잊혀진 들판",
      "gender": "female",
      "genre": "로맨스",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1328105622210872.jpg",
      "copy": "혐관 로맨스 + 미친 작화 = #잊혀진 들판 💕 김수지 작가 x 스푼 작가 역대급 로맨스 신작! 지금 #카카오페이지 에서❤️‍🔥 #잊혀진들판 #kakaopage 0:00 / 0:54 HTTPS://PAGE.KAKAO.COM/ 지금 카카오페이지에서 Se",
      "advertiser": "kakaopage",
      "libId": "1328105622210872",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1355166749827804",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "괴담에 떨어져도 출근을 해야 하는구나",
      "gender": "all",
      "genre": "드라마",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1355166749827804.jpg",
      "copy": "🎊원작 3.7억뷰 #괴담출근 웹툰 론칭🎊 여러분은 현장탐사팀으로 배정되셨습니다. 온보딩메이트는...👀 #괴담에떨어져도출근을해야하는구나 #카카오페이지 #kakaopage",
      "advertiser": "kakaopage",
      "libId": "1355166749827804",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_2622811508199470",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "흑표가문의 설표 아기님",
      "gender": "female",
      "genre": "로판",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_2622811508199470.jpg",
      "copy": "귀염뽀짝 아기가 야무지기까지 한데 어떻게 안 사랑해...💖 #흑표가문의설표아기님 #카카오페이지 #kakaopage KAKAOPAGE.ONELINK.ME Learn More KAKAOPAGE.ONELINK.ME Learn More KAKAOPAGE.ON",
      "advertiser": "kakaopage",
      "libId": "2622811508199470",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_989618093784565",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "괴담에 떨어져도 출근을 해야 하는구나",
      "gender": "all",
      "genre": "드라마",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_989618093784565.jpg",
      "copy": "🎊원작 3.7억뷰 #괴담출근 웹툰 론칭🎊 괴담 회사에 엘리트 신입 등장!? #괴담에떨어져도출근을해야하는구나 #카카오페이지 #kakaopage HTTPS://PAGE.KAKAO.COM/ Learn More HTTPS://PAGE.KAKAO.COM/ Le",
      "advertiser": "kakaopage",
      "libId": "989618093784565",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1310220397992161",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "괴담에 떨어져도 출근을 해야 하는구나",
      "gender": "all",
      "genre": "드라마",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1310220397992161.jpg",
      "copy": "🎊원작 3.7억뷰 #괴담출근 웹툰 론칭🎊 백일몽 주식회사 엘리트 신입사원 김솔음의 입사 첫날 따끈 후기 #괴담에떨어져도출근을해야하는구나 #카카오페이지 #kakaopage HTTPS://PAGE.KAKAO.COM/ Learn More HTTPS://PA",
      "advertiser": "kakaopage",
      "libId": "1310220397992161",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1460022602812372",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "괴담에 떨어져도 출근을 해야 하는구나",
      "gender": "all",
      "genre": "드라마",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1460022602812372.jpg",
      "copy": "🎊원작 3.7억뷰 #괴담출근 웹툰 론칭🎊 비운의 현장탐사팀 D조에 배정된 김솔음, 그리고 전원 사망 위기에 처한 D조의 운명은? #괴담에떨어져도출근을해야하는구나 #카카오페이지 #kakaopage 0:00 / 0:59 HTTPS://PAGE.KAKAO.",
      "advertiser": "kakaopage",
      "libId": "1460022602812372",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_2012729819613407",
      "competitor": "카카오페이지",
      "media": "meta",
      "work_title": "(로판 추천)",
      "gender": "female",
      "genre": "로판",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_2012729819613407.jpg",
      "copy": "로판 권태기에는 더 큰 자극으로! #카카오페이지 가 고자극 웹소 엄선해왔어🍽️ #kakaopage FB.COM 지금 카카오페이지에서 더 알아보기",
      "advertiser": "kakaopage",
      "libId": "2012729819613407",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1519632206245540",
      "competitor": "리디",
      "media": "meta",
      "work_title": "터치 유어 바디",
      "gender": "female",
      "genre": "BL",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1519632206245540.jpg",
      "copy": "선배가 원하는 게 제 몸이라고요? 윤 씨 가문의 4대 독자 윤서호. 사고 치고 유배당한 시골 마을에서 수상한 선배 이보듬을 만난다. 그런데 이 사람... 원하는 게 내 '몸이'었어?! 리디 웹툰 <터치 유어 바디> 지금 보러가기 👇 #리디웹툰 #리디온",
      "advertiser": "리디",
      "libId": "1519632206245540",
      "first_seen": "2026-04-23",
      "last_seen": "2026-06-11",
      "duration_days": 50,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_2008885979694435",
      "competitor": "리디",
      "media": "meta",
      "work_title": "백조 무덤",
      "gender": "female",
      "genre": "로판",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_2008885979694435.jpg",
      "copy": "“내 아내 대신이 되어라.” 차원 이동자 안나는 원래 세계로 돌아가는 방법을 찾기 위해 ‘백조 무덤’이라는 흉흉한 별칭을 가진 후작저에 하녀로 들어간다. 그곳에서 우연히 맞닥뜨린 후작 로트바르트, 안나를 사라진 자신의 부인이라 오해하여 강제로 취한 그",
      "advertiser": "리디",
      "libId": "2008885979694435",
      "first_seen": "2026-05-02",
      "last_seen": "2026-06-11",
      "duration_days": 41,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_825526206742486",
      "competitor": "리디",
      "media": "meta",
      "work_title": "안개를 삼킨 나비",
      "gender": "female",
      "genre": "로판",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_825526206742486.jpg",
      "copy": "\"난 처음부터 알고 있었어. 너랑 나랑 언젠가 이렇게 될 줄\" 아카데미 수석이자 난봉꾼인 일렉스와 한 침대에 눕게 된 영문이 궁금하다면?! 시즌1 완결된 김에 정주행도 가능한 리디 웹툰 <안개를 삼킨 나비> 지금 리디에서 바로 확인하세요 👇 #리디웹툰",
      "advertiser": "리디",
      "libId": "825526206742486",
      "first_seen": "2026-04-20",
      "last_seen": "2026-06-11",
      "duration_days": 53,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1426282002521128",
      "competitor": "리디",
      "media": "meta",
      "work_title": "백조 무덤",
      "gender": "female",
      "genre": "로판",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1426282002521128.jpg",
      "copy": "“내 아내 대신이 되어라.” 차원 이동자 안나는 원래 세계로 돌아가는 방법을 찾기 위해 ‘백조 무덤’이라는 흉흉한 별칭을 가진 후작저에 하녀로 들어간다. 그곳에서 우연히 맞닥뜨린 후작 로트바르트, 안나를 사라진 자신의 부인이라 오해하여 강제로 취한 그",
      "advertiser": "리디",
      "libId": "1426282002521128",
      "first_seen": "2026-05-13",
      "last_seen": "2026-06-11",
      "duration_days": 30,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1621531198961111",
      "competitor": "리디",
      "media": "meta",
      "work_title": "순경 씨와 나",
      "gender": "all",
      "genre": "드라마",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1621531198961111.jpg",
      "copy": "SNS에서 핫한 그 만화, 드디어 리디 상륙! 최근 시골 마을에 온 경찰관, 바보 같이 착해 보인 줄 알았는데...? 불량 여고생과 주재소 경찰관 서로 다른 두 사람의 성장 드라마! 리디 만화 <순경 씨와 나> 지금 보러가기👇 리디 만화 <순경 씨와 ",
      "advertiser": "리디",
      "libId": "1621531198961111",
      "first_seen": "2026-05-19",
      "last_seen": "2026-06-11",
      "duration_days": 24,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_866501443167216",
      "competitor": "리디",
      "media": "meta",
      "work_title": "이세계 착각 헌터",
      "gender": "male",
      "genre": "판타지",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_866501443167216.jpg",
      "copy": "이세계 착각 헌터 e북 드디어 완결 👽 💚 세트 최대 37% 할인 💚 든든한 포인트백까지 기려와 함께했던 이야기의 끝을 역대급 혜택과 함께 지금 리디에서 만나보세요! #리디 #리디판타지 #이착헌 #e북완결 리디 웹소설 <이세계 착각 헌터> e북 완결 ",
      "advertiser": "리디",
      "libId": "866501443167216",
      "first_seen": "2026-06-01",
      "last_seen": "2026-06-11",
      "duration_days": 11,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_2111944149537977",
      "competitor": "리디",
      "media": "meta",
      "work_title": "오월의 정원에서",
      "gender": "female",
      "genre": "로판",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_2111944149537977.jpg",
      "copy": "“신께 맹세코, 죽어도 내가 먼저 사랑한다고 말할 일은 없을 거야.” 부모님의 죽음 이후 바네사를 기다리고 있는 것은 막대한 빚과 원치 않는 결혼이었다. 혼약을 어그러트리기 위해서는 추문이 필요했고, '정원사' 시어도어는 너무나 완벽한 상대였을 뿐이다",
      "advertiser": "리디",
      "libId": "2111944149537977",
      "first_seen": "2026-05-18",
      "last_seen": "2026-06-11",
      "duration_days": 25,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_2039727653420603",
      "competitor": "리디",
      "media": "meta",
      "work_title": "터치 유어 바디",
      "gender": "female",
      "genre": "BL",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_2039727653420603.jpg",
      "copy": "선배가 원하는 게 제 몸이라고요? 윤 씨 가문의 4대 독자 윤서호. 사고 치고 유배당한 시골 마을에서 수상한 선배 이보듬을 만난다. 그런데 이 사람... 원하는 게 내 '몸이'었어?! 리디 웹툰 <터치 유어 바디> 지금 보러가기 👇 #리디웹툰 #리디온",
      "advertiser": "리디",
      "libId": "2039727653420603",
      "first_seen": "2026-04-30",
      "last_seen": "2026-06-11",
      "duration_days": 43,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1514470123665095",
      "competitor": "리디",
      "media": "meta",
      "work_title": "(미상)",
      "gender": "female",
      "genre": "로맨스",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1514470123665095.jpg",
      "copy": "\"넌 우릴 포기하고 있어. 날 버리고 있어.\" S급 에스퍼 국영과 일반인 의사 한아의 결혼. 한아는 국영이 죽어가는 것을 그저 바라볼 수밖에 없다. 그때 나타난 스물 한 살의 어린 가이드. 한아는 남편을 살리기 위해, 기꺼이 가이드를 국영에게 붙이는데",
      "advertiser": "리디",
      "libId": "1514470123665095",
      "first_seen": "2026-05-31",
      "last_seen": "2026-06-11",
      "duration_days": 12,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_901658552885016",
      "competitor": "리디",
      "media": "meta",
      "work_title": "꽃은 미끼야",
      "gender": "female",
      "genre": "로맨스",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_901658552885016.jpg",
      "copy": "<꽃은 미끼야> 시즌2 시작했어요! 💐 나를 죽이려 한 살인마와의 아슬아슬한 결혼생활. 과연 언제까지 들키지 않을 수 있을까? 리디에서 무료로 시작하기 👇 #리디웹툰 #웹툰추천 #로맨스 #현대물 #꽃은미끼야 리디 웹툰 <꽃은 미끼야> Learn Mor",
      "advertiser": "리디",
      "libId": "901658552885016",
      "first_seen": "2026-04-30",
      "last_seen": "2026-06-11",
      "duration_days": 43,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_941597488674445",
      "competitor": "리디",
      "media": "meta",
      "work_title": "헌터는 조용히 살고 싶다",
      "gender": "female",
      "genre": "BL",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_941597488674445.jpg",
      "copy": "조용히 살고 싶었던 S급 헌터의 파란만장한 수난기! 💥 세상을 구하고 은퇴를 꿈꿨건만, 자꾸만 꼬여버리는 일상과 그 앞에 나타난 수상한 인연들?! 과연 그는 평화로운 삶을 되찾을 수 있을까요? 🏠🏃‍♂️ 리디 웹툰 <헌터는 조용히 살고 싶다 지금 리디",
      "advertiser": "리디",
      "libId": "941597488674445",
      "first_seen": "2026-04-30",
      "last_seen": "2026-06-11",
      "duration_days": 43,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_958130190445439",
      "competitor": "리디",
      "media": "meta",
      "work_title": "코드네임 아나스타샤",
      "gender": "female",
      "genre": "BL",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_958130190445439.jpg",
      "copy": "국정원 에이스 요원 권택주는 모스크바로 파견되어 파트너 ‘제냐’를 만나게 된다. 화려한 외모와 어울리지 않는 폭력성은 권택주를 긴장하게 하는데... 리디 웹툰 <코드네임 아나스타샤> 지금 보러가기👇 #리디 #리디BL #리디온리 #배틀연애 리디 BL웹툰",
      "advertiser": "리디",
      "libId": "958130190445439",
      "first_seen": "2026-05-14",
      "last_seen": "2026-06-11",
      "duration_days": 29,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1183430463885633",
      "competitor": "리디",
      "media": "meta",
      "work_title": "디자이어 미 이프 유 캔",
      "gender": "female",
      "genre": "BL",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1183430463885633.jpg",
      "copy": "ZIG 작가의 BL소설이 웹툰으로 왔다! <디자이어 미 이프 유 캔> 운명의 상대를 찾는다며 난잡하게 행동하는 극알파 그레이슨 어느 날, 소방관 데인을 만나게 되는데... 그가 바로 자신의 운명의 상대임을 느끼게 된다! BL웹툰 <디자이어 미 이프 유",
      "advertiser": "리디",
      "libId": "1183430463885633",
      "first_seen": "2026-05-31",
      "last_seen": "2026-06-11",
      "duration_days": 12,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1496818802115025",
      "competitor": "리디",
      "media": "meta",
      "work_title": "벨 푸페의 슈퍼달링 약혼",
      "gender": "female",
      "genre": "로판",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1496818802115025.jpg",
      "copy": "\"내 취향 아니야\"라던 까칠한 황자님을 반드시 행복하게 해주겠다는 공작 영애! 🤫👑 사랑스러운 외모에 숨겨진 영애의 본성이 궁금하다면? 화제의 신작 <벨 푸페의 슈퍼달링 약혼> 기다릴 필요 없이 지금 바로 리디에서 시작하세요! #리디 #벨푸페의슈퍼달링",
      "advertiser": "리디",
      "libId": "1496818802115025",
      "first_seen": "2026-04-30",
      "last_seen": "2026-06-11",
      "duration_days": 43,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_4397666337155456",
      "competitor": "리디",
      "media": "meta",
      "work_title": "오월의 정원에서",
      "gender": "female",
      "genre": "로판",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_4397666337155456.jpg",
      "copy": "“신께 맹세코, 죽어도 내가 먼저 사랑한다고 말할 일은 없을 거야.” 부모님의 죽음 이후 바네사를 기다리고 있는 것은 막대한 빚과 원치 않는 결혼이었다. 혼약을 어그러트리기 위해서는 추문이 필요했고, '정원사' 시어도어는 너무나 완벽한 상대였을 뿐이다",
      "advertiser": "리디",
      "libId": "4397666337155456",
      "first_seen": "2026-05-18",
      "last_seen": "2026-06-11",
      "duration_days": 25,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_989070566965581",
      "competitor": "리디",
      "media": "meta",
      "work_title": "코드네임 아나스타샤",
      "gender": "female",
      "genre": "BL",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_989070566965581.jpg",
      "copy": "국정원 에이스 요원 권택주는 모스크바로 파견되어 파트너 ‘제냐’를 만나게 된다. 화려한 외모와 어울리지 않는 폭력성은 권택주를 긴장하게 하는데... 리디 웹툰 <코드네임 아나스타샤> 지금 보러가기👇 #리디 #리디BL #리디온리 #배틀연애 0:00 / ",
      "advertiser": "리디",
      "libId": "989070566965581",
      "first_seen": "2026-05-01",
      "last_seen": "2026-06-11",
      "duration_days": 42,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_26785108714475397",
      "competitor": "리디",
      "media": "meta",
      "work_title": "우리 흑마도사가 너무 귀여워!",
      "gender": "female",
      "genre": "로판",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_26785108714475397.jpg",
      "copy": "흑마도사 제이드는 사실 츤데레였다?! 마법학교 우등생 아리아는 후배들을 지도하는 감독생이지만, 문제아 제이드 때문에 속을 썩이고 있었다. 흑마도사 일족으로 주변에 반항적인 그는 모두에게 공포의 대상이지만, 아리아가 그와 접촉한 순간 이상한 목소리가 들",
      "advertiser": "리디",
      "libId": "26785108714475397",
      "first_seen": "2026-04-30",
      "last_seen": "2026-06-11",
      "duration_days": 43,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1559627242443471",
      "competitor": "리디",
      "media": "meta",
      "work_title": "해피투게더",
      "gender": "female",
      "genre": "BL",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1559627242443471.jpg",
      "copy": "날파리헌터 <해피투게더> 드디어 시즌 2 컴백! 🎉 모두의 인생작이 되어버린 바로 그 작품! 승민과 재영, 두 사람 앞에 벌어질 일들이 궁금하다면? 지금 바로 리디에서 만나보세요 👇 #리디 #리디BL #벨툰 #승쟁 RIDI ONLY <해피투게더> Le",
      "advertiser": "리디",
      "libId": "1559627242443471",
      "first_seen": "2026-06-01",
      "last_seen": "2026-06-11",
      "duration_days": 11,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1252475916705415",
      "competitor": "리디",
      "media": "meta",
      "work_title": "오월의 정원에서",
      "gender": "female",
      "genre": "로판",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1252475916705415.jpg",
      "copy": "“신께 맹세코, 죽어도 내가 먼저 사랑한다고 말할 일은 없을 거야.” 부모님의 죽음 이후 바네사를 기다리고 있는 것은 막대한 빚과 원치 않는 결혼이었다. 혼약을 어그러트리기 위해서는 추문이 필요했고, '정원사' 시어도어는 너무나 완벽한 상대였을 뿐이다",
      "advertiser": "리디",
      "libId": "1252475916705415",
      "first_seen": "2026-05-18",
      "last_seen": "2026-06-11",
      "duration_days": 25,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_849069811580461",
      "competitor": "리디",
      "media": "meta",
      "work_title": "꽃은 미끼야",
      "gender": "female",
      "genre": "로맨스",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_849069811580461.jpg",
      "copy": "<꽃은 미끼야> 시즌2 시작했어요! 💐 나를 죽이려 한 살인마와의 아슬아슬한 결혼생활. 과연 언제까지 들키지 않을 수 있을까? 리디에서 무료로 시작하기 👇 #리디웹툰 #웹툰추천 #로맨스 #현대물 #꽃은미끼야 리디 웹툰 <꽃은 미끼야> 시즌 2 Lear",
      "advertiser": "리디",
      "libId": "849069811580461",
      "first_seen": "2026-04-30",
      "last_seen": "2026-06-11",
      "duration_days": 43,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_927522446642927",
      "competitor": "리디",
      "media": "meta",
      "work_title": "안개를 삼킨 나비",
      "gender": "female",
      "genre": "로판",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_927522446642927.jpg",
      "copy": "\"난 처음부터 알고 있었어. 너랑 나랑 언젠가 이렇게 될 줄\" 아카데미 수석이자 난봉꾼인 일렉스와 한 침대에 눕게 된 영문이 궁금하다면?! 시즌1 완결된 김에 정주행도 가능한 리디 웹툰 <안개를 삼킨 나비> 지금 리디에서 바로 확인하세요 👇 #리디웹툰",
      "advertiser": "리디",
      "libId": "927522446642927",
      "first_seen": "2026-05-11",
      "last_seen": "2026-06-11",
      "duration_days": 32,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_972985818551117",
      "competitor": "리디",
      "media": "meta",
      "work_title": "이딴 게 우렁각시?!",
      "gender": "female",
      "genre": "로맨스",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_972985818551117.jpg",
      "copy": "형사님, 저는 언제나 당신의 신부가 되고 싶었어요! 형사 시절, 사정이 딱해서 도와줬던 여자애가 은혜를 갚겠다며 집에 찾아왔다?! 웹툰 <이딴 게 우렁각시?!> 지금 리디에서 확인해보세요👇 #리디웹툰 #웹툰추천 #로맨스 #신유리 리디 웹툰 <이딴 게 ",
      "advertiser": "리디",
      "libId": "972985818551117",
      "first_seen": "2026-04-30",
      "last_seen": "2026-06-11",
      "duration_days": 43,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1474003860592355",
      "competitor": "리디",
      "media": "meta",
      "work_title": "(미상)",
      "gender": "female",
      "genre": "로맨스",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1474003860592355.jpg",
      "copy": "\"넌 우릴 포기하고 있어. 날 버리고 있어.\" S급 에스퍼 국영과 일반인 의사 한아의 결혼. 한아는 국영이 죽어가는 것을 그저 바라볼 수밖에 없다. 그때 나타난 스물 한 살의 어린 가이드. 한아는 남편을 살리기 위해, 기꺼이 가이드를 국영에게 붙이는데",
      "advertiser": "리디",
      "libId": "1474003860592355",
      "first_seen": "2026-05-31",
      "last_seen": "2026-06-11",
      "duration_days": 12,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1303661041281416",
      "competitor": "리디",
      "media": "meta",
      "work_title": "피자배달부와 골드팰리스",
      "gender": "female",
      "genre": "BL",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1303661041281416.jpg",
      "copy": "🍕<피자배달부와 골드팰리스> 완결🍕 우여곡절 끝에 서로에게 닿은 우원과 서안의 이야기, 지금 기다리면 무료로 만나보세요👇 #리디 #리디웹툰 #비엘 #완결 #피자배달부와골드팰리스 #피달부 <피자배달부와 골드팰리스> 완결 Learn More",
      "advertiser": "리디",
      "libId": "1303661041281416",
      "first_seen": "2026-05-19",
      "last_seen": "2026-06-11",
      "duration_days": 24,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_2065185550704046",
      "competitor": "리디",
      "media": "meta",
      "work_title": "안개를 삼킨 나비",
      "gender": "female",
      "genre": "로판",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_2065185550704046.jpg",
      "copy": "\"난 처음부터 알고 있었어. 너랑 나랑 언젠가 이렇게 될 줄\" 아카데미 수석이자 난봉꾼인 일렉스와 한 침대에 눕게 된 영문이 궁금하다면?! 시즌1 완결된 김에 정주행도 가능한 리디 웹툰 <안개를 삼킨 나비> 지금 리디에서 바로 확인하세요 👇 #리디웹툰",
      "advertiser": "리디",
      "libId": "2065185550704046",
      "first_seen": "2026-05-11",
      "last_seen": "2026-06-11",
      "duration_days": 32,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1943957396993741",
      "competitor": "리디",
      "media": "meta",
      "work_title": "순경 씨와 나",
      "gender": "all",
      "genre": "드라마",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1943957396993741.jpg",
      "copy": "SNS에서 핫한 그 만화, 드디어 리디 상륙! 최근 시골 마을에 온 경찰관, 바보 같이 착해 보인 줄 알았는데...? 불량 여고생과 주재소 경찰관 서로 다른 두 사람의 성장 드라마! 리디 만화 <순경 씨와 나> 지금 보러가기👇 리디 만화 <순경 씨와 ",
      "advertiser": "리디",
      "libId": "1943957396993741",
      "first_seen": "2026-05-19",
      "last_seen": "2026-06-11",
      "duration_days": 24,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1616784319412320",
      "competitor": "리디",
      "media": "meta",
      "work_title": "디자이어 미 이프 유 캔",
      "gender": "female",
      "genre": "BL",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1616784319412320.jpg",
      "copy": "ZIG 작가의 BL소설이 웹툰으로 왔다! <디자이어 미 이프 유 캔> 운명의 상대를 찾는다며 난잡하게 행동하는 극알파 그레이슨 어느 날, 소방관 데인을 만나게 되는데... 그가 바로 자신의 운명의 상대임을 느끼게 된다! BL웹툰 <디자이어 미 이프 유",
      "advertiser": "리디",
      "libId": "1616784319412320",
      "first_seen": "2026-05-31",
      "last_seen": "2026-06-11",
      "duration_days": 12,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1915494402511033",
      "competitor": "리디",
      "media": "meta",
      "work_title": "악역 영애 안의 사람",
      "gender": "female",
      "genre": "로판",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1915494402511033.jpg",
      "copy": "<악역 영애 안의 사람> 완결! 오직 리디에서 만나보세요 💙 어느 날, 여성향 게임의 악역 레밀리아는 이방인 에미에게 몸을 빼앗긴다. 에미에게 받아본 적 없던 사랑을 느낀 레밀리아는 그녀를 고통스럽게 한 자들에게 복수를 시작한다! <악역 영애 안의 사",
      "advertiser": "리디",
      "libId": "1915494402511033",
      "first_seen": "2026-04-30",
      "last_seen": "2026-06-11",
      "duration_days": 43,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1447328913813629",
      "competitor": "리디",
      "media": "meta",
      "work_title": "(미상)",
      "gender": "female",
      "genre": "로맨스",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1447328913813629.jpg",
      "copy": "\"넌 우릴 포기하고 있어. 날 버리고 있어.\" S급 에스퍼 국영과 일반인 의사 한아의 결혼. 한아는 국영이 죽어가는 것을 그저 바라볼 수밖에 없다. 그때 나타난 스물 한 살의 어린 가이드. 한아는 남편을 살리기 위해, 기꺼이 가이드를 국영에게 붙이는데",
      "advertiser": "리디",
      "libId": "1447328913813629",
      "first_seen": "2026-05-31",
      "last_seen": "2026-06-11",
      "duration_days": 12,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1515266829994518",
      "competitor": "리디",
      "media": "meta",
      "work_title": "(미상)",
      "gender": "female",
      "genre": "로맨스",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1515266829994518.jpg",
      "copy": "부모를 사고로 잃고, 오라버니의 빚 때문에 기방에 팔려온 유월. 오라버니에 대한 믿음을 버리지 못한 채 버티던 어느 날— 자신을 탐하려던 대감을 실수로 죽이고 만다. 그 장면을 목격한 수상한 한량, 태운. 그는 죄를 덮어주는 대신, 자신의 아이를 낳으",
      "advertiser": "리디",
      "libId": "1515266829994518",
      "first_seen": "2026-05-15",
      "last_seen": "2026-06-11",
      "duration_days": 28,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_5688980161328155",
      "competitor": "리디",
      "media": "meta",
      "work_title": "디자이어 미 이프 유 캔",
      "gender": "female",
      "genre": "BL",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_5688980161328155.jpg",
      "copy": "ZIG 작가의 BL소설이 웹툰으로 왔다! <디자이어 미 이프 유 캔> 운명의 상대를 찾는다며 난잡하게 행동하는 극알파 그레이슨 어느 날, 소방관 데인을 만나게 되는데... 그가 바로 자신의 운명의 상대임을 느끼게 된다! BL웹툰 <디자이어 미 이프 유",
      "advertiser": "리디",
      "libId": "5688980161328155",
      "first_seen": "2026-05-31",
      "last_seen": "2026-06-11",
      "duration_days": 12,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_36048220554792443",
      "competitor": "리디",
      "media": "meta",
      "work_title": "이세계 착각 헌터",
      "gender": "male",
      "genre": "판타지",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_36048220554792443.jpg",
      "copy": "이세계 착각 헌터 e북 드디어 완결 👽 💚 세트 최대 37% 할인 💚 든든한 포인트백까지 기려와 함께했던 이야기의 끝을 역대급 혜택과 함께 지금 리디에서 만나보세요! #리디 #리디판타지 #이착헌 #e북완결 리디 웹소설 <이세계 착각 헌터> e북 완결 ",
      "advertiser": "리디",
      "libId": "36048220554792443",
      "first_seen": "2026-06-02",
      "last_seen": "2026-06-11",
      "duration_days": 10,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1533273611690535",
      "competitor": "리디",
      "media": "meta",
      "work_title": "안개를 삼킨 나비",
      "gender": "female",
      "genre": "로판",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1533273611690535.jpg",
      "copy": "\"난 처음부터 알고 있었어. 너랑 나랑 언젠가 이렇게 될 줄\" 아카데미 수석이자 난봉꾼인 일렉스와 한 침대에 눕게 된 영문이 궁금하다면?! 시즌1 완결된 김에 정주행도 가능한 리디 웹툰 <안개를 삼킨 나비> 지금 리디에서 바로 확인하세요 👇 #리디웹툰",
      "advertiser": "리디",
      "libId": "1533273611690535",
      "first_seen": "2026-06-08",
      "last_seen": "2026-06-11",
      "duration_days": 4,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_2404410963375527",
      "competitor": "리디",
      "media": "meta",
      "work_title": "이세계 착각 헌터",
      "gender": "male",
      "genre": "판타지",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_2404410963375527.jpg",
      "copy": "이세계 착각 헌터 e북 드디어 완결 👽 💚 세트 최대 37% 할인 💚 든든한 포인트백까지 기려와 함께했던 이야기의 끝을 역대급 혜택과 함께 지금 리디에서 만나보세요! #리디 #리디판타지 #이착헌 #e북완결 리디 웹소설 <이세계 착각 헌터> e북 완결 ",
      "advertiser": "리디",
      "libId": "2404410963375527",
      "first_seen": "2026-06-02",
      "last_seen": "2026-06-11",
      "duration_days": 10,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_952769814054253",
      "competitor": "리디",
      "media": "meta",
      "work_title": "순경 씨와 나",
      "gender": "all",
      "genre": "드라마",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_952769814054253.jpg",
      "copy": "SNS에서 핫한 그 만화, 드디어 리디 상륙! 최근 시골 마을에 온 경찰관, 바보 같이 착해 보인 줄 알았는데...? 불량 여고생과 주재소 경찰관 서로 다른 두 사람의 성장 드라마! 리디 만화 <순경 씨와 나> 지금 보러가기👇 리디 만화 <순경 씨와 ",
      "advertiser": "리디",
      "libId": "952769814054253",
      "first_seen": "2026-05-20",
      "last_seen": "2026-06-11",
      "duration_days": 23,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1678189733385988",
      "competitor": "리디",
      "media": "meta",
      "work_title": "이세계 착각 헌터",
      "gender": "male",
      "genre": "판타지",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1678189733385988.jpg",
      "copy": "이세계 착각 헌터 e북 드디어 완결 👽 💚 세트 최대 37% 할인 💚 든든한 포인트백까지 기려와 함께했던 이야기의 끝을 역대급 혜택과 함께 지금 리디에서 만나보세요! #리디 #리디판타지 #이착헌 #e북완결 리디 웹소설 <이세계 착각 헌터> e북 완결 ",
      "advertiser": "리디",
      "libId": "1678189733385988",
      "first_seen": "2026-06-02",
      "last_seen": "2026-06-11",
      "duration_days": 10,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_2565861587193138",
      "competitor": "리디",
      "media": "meta",
      "work_title": "오월의 정원에서",
      "gender": "female",
      "genre": "로판",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_2565861587193138.jpg",
      "copy": "“신께 맹세코, 죽어도 내가 먼저 사랑한다고 말할 일은 없을 거야.” 부모님의 죽음 이후 바네사를 기다리고 있는 것은 막대한 빚과 원치 않는 결혼이었다. 혼약을 어그러트리기 위해서는 추문이 필요했고, '정원사' 시어도어는 너무나 완벽한 상대였을 뿐이다",
      "advertiser": "리디",
      "libId": "2565861587193138",
      "first_seen": "2026-05-18",
      "last_seen": "2026-06-11",
      "duration_days": 25,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_3898330470297365",
      "competitor": "리디",
      "media": "meta",
      "work_title": "(미상)",
      "gender": "female",
      "genre": "로맨스",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_3898330470297365.jpg",
      "copy": "부모를 사고로 잃고, 오라버니의 빚 때문에 기방에 팔려온 유월. 오라버니에 대한 믿음을 버리지 못한 채 버티던 어느 날— 자신을 탐하려던 대감을 실수로 죽이고 만다. 그 장면을 목격한 수상한 한량, 태운. 그는 죄를 덮어주는 대신, 자신의 아이를 낳으",
      "advertiser": "리디",
      "libId": "3898330470297365",
      "first_seen": "2026-05-15",
      "last_seen": "2026-06-11",
      "duration_days": 28,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_2463134990799252",
      "competitor": "리디",
      "media": "meta",
      "work_title": "터치 유어 바디",
      "gender": "female",
      "genre": "BL",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_2463134990799252.jpg",
      "copy": "선배가 원하는 게 제 몸이라고요? 윤 씨 가문의 4대 독자 윤서호. 사고 치고 유배당한 시골 마을에서 수상한 선배 이보듬을 만난다. 그런데 이 사람... 원하는 게 내 '몸이'었어?! 리디 웹툰 <터치 유어 바디> 지금 보러가기 👇 #리디웹툰 #리디온",
      "advertiser": "리디",
      "libId": "2463134990799252",
      "first_seen": "2026-04-30",
      "last_seen": "2026-06-11",
      "duration_days": 43,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_2190142195133318",
      "competitor": "리디",
      "media": "meta",
      "work_title": "(미상)",
      "gender": "female",
      "genre": "로맨스",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_2190142195133318.jpg",
      "copy": "\"넌 우릴 포기하고 있어. 날 버리고 있어.\" S급 에스퍼 국영과 일반인 의사 한아의 결혼. 한아는 국영이 죽어가는 것을 그저 바라볼 수밖에 없다. 그때 나타난 스물 한 살의 어린 가이드. 한아는 남편을 살리기 위해, 기꺼이 가이드를 국영에게 붙이는데",
      "advertiser": "리디",
      "libId": "2190142195133318",
      "first_seen": "2026-05-31",
      "last_seen": "2026-06-11",
      "duration_days": 12,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1340777194626626",
      "competitor": "리디",
      "media": "meta",
      "work_title": "디자이어 미 이프 유 캔",
      "gender": "female",
      "genre": "BL",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1340777194626626.jpg",
      "copy": "ZIG 작가의 BL소설이 웹툰으로 왔다! <디자이어 미 이프 유 캔> 운명의 상대를 찾는다며 난잡하게 행동하는 극알파 그레이슨 어느 날, 소방관 데인을 만나게 되는데... 그가 바로 자신의 운명의 상대임을 느끼게 된다! BL웹툰 <디자이어 미 이프 유",
      "advertiser": "리디",
      "libId": "1340777194626626",
      "first_seen": "2026-05-31",
      "last_seen": "2026-06-11",
      "duration_days": 12,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_978637078254490",
      "competitor": "리디",
      "media": "meta",
      "work_title": "디자이어 미 이프 유 캔",
      "gender": "female",
      "genre": "BL",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_978637078254490.jpg",
      "copy": "ZIG 작가의 BL소설이 웹툰으로 왔다! <디자이어 미 이프 유 캔> 운명의 상대를 찾는다며 난잡하게 행동하는 극알파 그레이슨 어느 날, 소방관 데인을 만나게 되는데... 그가 바로 자신의 운명의 상대임을 느끼게 된다! BL웹툰 <디자이어 미 이프 유",
      "advertiser": "리디",
      "libId": "978637078254490",
      "first_seen": "2026-05-31",
      "last_seen": "2026-06-11",
      "duration_days": 12,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1720507946051062",
      "competitor": "리디",
      "media": "meta",
      "work_title": "디자이어 미 이프 유 캔",
      "gender": "female",
      "genre": "BL",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1720507946051062.jpg",
      "copy": "ZIG 작가의 BL소설이 웹툰으로 왔다! <디자이어 미 이프 유 캔> 운명의 상대를 찾는다며 난잡하게 행동하는 극알파 그레이슨 어느 날, 소방관 데인을 만나게 되는데... 그가 바로 자신의 운명의 상대임을 느끼게 된다! BL웹툰 <디자이어 미 이프 유",
      "advertiser": "리디",
      "libId": "1720507946051062",
      "first_seen": "2026-05-31",
      "last_seen": "2026-06-11",
      "duration_days": 12,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1913595915956269",
      "competitor": "리디",
      "media": "meta",
      "work_title": "터치 유어 바디",
      "gender": "female",
      "genre": "BL",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1913595915956269.jpg",
      "copy": "선배가 원하는 게 제 몸이라고요? 윤 씨 가문의 4대 독자 윤서호. 사고 치고 유배당한 시골 마을에서 수상한 선배 이보듬을 만난다. 그런데 이 사람... 원하는 게 내 '몸이'었어?! 리디 웹툰 <터치 유어 바디> 지금 보러가기 👇 #리디웹툰 #리디온",
      "advertiser": "리디",
      "libId": "1913595915956269",
      "first_seen": "2026-04-30",
      "last_seen": "2026-06-11",
      "duration_days": 43,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1779005559732209",
      "competitor": "리디",
      "media": "meta",
      "work_title": "(미상)",
      "gender": "female",
      "genre": "로맨스",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1779005559732209.jpg",
      "copy": "\"넌 우릴 포기하고 있어. 날 버리고 있어.\" S급 에스퍼 국영과 일반인 의사 한아의 결혼. 한아는 국영이 죽어가는 것을 그저 바라볼 수밖에 없다. 그때 나타난 스물 한 살의 어린 가이드. 한아는 남편을 살리기 위해, 기꺼이 가이드를 국영에게 붙이는데",
      "advertiser": "리디",
      "libId": "1779005559732209",
      "first_seen": "2026-06-07",
      "last_seen": "2026-06-11",
      "duration_days": 5,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_828577010322024",
      "competitor": "리디",
      "media": "meta",
      "work_title": "터치 유어 바디",
      "gender": "female",
      "genre": "BL",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_828577010322024.jpg",
      "copy": "선배가 원하는 게 제 몸이라고요? 윤 씨 가문의 4대 독자 윤서호. 사고 치고 유배당한 시골 마을에서 수상한 선배 이보듬을 만난다. 그런데 이 사람... 원하는 게 내 '몸이'었어?! 리디 웹툰 <터치 유어 바디> 지금 보러가기 👇 #리디웹툰 #리디온",
      "advertiser": "리디",
      "libId": "828577010322024",
      "first_seen": "2026-05-01",
      "last_seen": "2026-06-11",
      "duration_days": 42,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1524849029007263",
      "competitor": "리디",
      "media": "meta",
      "work_title": "터치 유어 바디",
      "gender": "female",
      "genre": "BL",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1524849029007263.jpg",
      "copy": "선배가 원하는 게 제 몸이라고요? 윤 씨 가문의 4대 독자 윤서호. 사고 치고 유배당한 시골 마을에서 수상한 선배 이보듬을 만난다. 그런데 이 사람... 원하는 게 내 '몸이'었어?! 리디 웹툰 <터치 유어 바디> 지금 보러가기 👇 #리디웹툰 #리디온",
      "advertiser": "리디",
      "libId": "1524849029007263",
      "first_seen": "2026-05-01",
      "last_seen": "2026-06-11",
      "duration_days": 42,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1773896626912277",
      "competitor": "리디",
      "media": "meta",
      "work_title": "오월의 정원에서",
      "gender": "female",
      "genre": "로판",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1773896626912277.jpg",
      "copy": "“신께 맹세코, 죽어도 내가 먼저 사랑한다고 말할 일은 없을 거야.” 부모님의 죽음 이후 바네사를 기다리고 있는 것은 막대한 빚과 원치 않는 결혼이었다. 혼약을 어그러트리기 위해서는 추문이 필요했고, '정원사' 시어도어는 너무나 완벽한 상대였을 뿐이다",
      "advertiser": "리디",
      "libId": "1773896626912277",
      "first_seen": "2026-05-19",
      "last_seen": "2026-06-11",
      "duration_days": 24,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1207637314707803",
      "competitor": "리디",
      "media": "meta",
      "work_title": "디자이어 미 이프 유 캔",
      "gender": "female",
      "genre": "BL",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1207637314707803.jpg",
      "copy": "ZIG 작가의 BL소설이 웹툰으로 왔다! <디자이어 미 이프 유 캔> 운명의 상대를 찾는다며 난잡하게 행동하는 극알파 그레이슨 어느 날, 소방관 데인을 만나게 되는데... 그가 바로 자신의 운명의 상대임을 느끼게 된다! BL웹툰 <디자이어 미 이프 유",
      "advertiser": "리디",
      "libId": "1207637314707803",
      "first_seen": "2026-05-31",
      "last_seen": "2026-06-11",
      "duration_days": 12,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1028558140123727",
      "competitor": "리디",
      "media": "meta",
      "work_title": "헌터는 조용히 살고 싶다",
      "gender": "female",
      "genre": "BL",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1028558140123727.jpg",
      "copy": "조용히 살고 싶었던 S급 헌터의 파란만장한 수난기! 💥 세상을 구하고 은퇴를 꿈꿨건만, 자꾸만 꼬여버리는 일상과 그 앞에 나타난 수상한 인연들?! 과연 그는 평화로운 삶을 되찾을 수 있을까요? 🏠🏃‍♂️ 리디 웹툰 <헌터는 조용히 살고 싶다> 지금 리",
      "advertiser": "리디",
      "libId": "1028558140123727",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1381444210539011",
      "competitor": "리디",
      "media": "meta",
      "work_title": "헌터는 조용히 살고 싶다",
      "gender": "female",
      "genre": "BL",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1381444210539011.jpg",
      "copy": "조용히 살고 싶었던 S급 헌터의 파란만장한 수난기! 💥 세상을 구하고 은퇴를 꿈꿨건만, 자꾸만 꼬여버리는 일상과 그 앞에 나타난 수상한 인연들?! 과연 그는 평화로운 삶을 되찾을 수 있을까요? 🏠🏃‍♂️ 리디 웹툰 <헌터는 조용히 살고 싶다> 지금 리",
      "advertiser": "리디",
      "libId": "1381444210539011",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_36823044640627206",
      "competitor": "리디",
      "media": "meta",
      "work_title": "코드네임 아나스타샤",
      "gender": "female",
      "genre": "BL",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_36823044640627206.jpg",
      "copy": "국정원 에이스 요원 권택주는 모스크바로 파견되어 파트너 ‘제냐’를 만나게 된다. 화려한 외모와 어울리지 않는 폭력성은 권택주를 긴장하게 하는데... 리디 웹툰 <코드네임 아나스타샤> 지금 보러가기👇 #리디 #리디BL #리디온리 #배틀연애 0:00 / ",
      "advertiser": "리디",
      "libId": "36823044640627206",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1278598510925993",
      "competitor": "리디",
      "media": "meta",
      "work_title": "코드네임 아나스타샤",
      "gender": "female",
      "genre": "BL",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1278598510925993.jpg",
      "copy": "국정원 에이스 요원 권택주는 모스크바로 파견되어 파트너 ‘제냐’를 만나게 된다. 화려한 외모와 어울리지 않는 폭력성은 권택주를 긴장하게 하는데... 리디 웹툰 <코드네임 아나스타샤> 지금 보러가기👇 #리디 #리디BL #리디온리 #배틀연애 리디 BL웹툰",
      "advertiser": "리디",
      "libId": "1278598510925993",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1687377732311478",
      "competitor": "네이버웹툰",
      "media": "meta",
      "work_title": "취사병 전설이 되다",
      "gender": "male",
      "genre": "일상",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1687377732311478.jpg",
      "copy": "2개에서 이 크리에이티브 및 문구를 사용합니다 드롭다운 열기 ​ 요약 세부 사항 보기 dokgo_chorong 페이지는 네이버 웹툰과(와) 함께합니다 광고 일병이 사단장 앞에서 욕 갈김; #웹툰추천 #취사병전설이되다 #네이버웹툰 0:00 / 0:50",
      "advertiser": "nwebtoon",
      "libId": "1687377732311478",
      "first_seen": "2026-06-07",
      "last_seen": "2026-06-11",
      "duration_days": 5,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1455611816610472",
      "competitor": "네이버웹툰",
      "media": "meta",
      "work_title": "취사병 전설이 되다",
      "gender": "male",
      "genre": "일상",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1455611816610472.jpg",
      "copy": "상세 정보 보기 fabbbb.25 페이지는 네이버 웹툰과(와) 함께합니다 광고 군대리아🫡🍔❤️ 여러분도 웹툰 ’취사병 전설이 되다‘ 보고 요리 스텟 올려보세요! #네이버웹툰 #취사병전설이되다 #웹툰 #군대 #웹툰추천 0:00 / 0:41 WEBTOON",
      "advertiser": "nwebtoon",
      "libId": "1455611816610472",
      "first_seen": "2026-06-07",
      "last_seen": "2026-06-11",
      "duration_days": 5,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1324626809821588",
      "competitor": "네이버웹툰",
      "media": "meta",
      "work_title": "취사병 전설이 되다",
      "gender": "male",
      "genre": "일상",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1324626809821588.jpg",
      "copy": "상세 정보 보기 dokgo_chorong 페이지는 네이버 웹툰과(와) 함께합니다 광고 짬찌 탈출하나 했더니... 후임 상태가? #웹툰#리뷰 #웹툰리뷰 #웹툰추천 #취사병전설이되다 #네이버웹툰 0:00 / 0:43 WEBTOON.ONELINK.ME do",
      "advertiser": "nwebtoon",
      "libId": "1324626809821588",
      "first_seen": "2026-06-07",
      "last_seen": "2026-06-11",
      "duration_days": 5,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_844506761666180",
      "competitor": "네이버웹툰",
      "media": "meta",
      "work_title": "취사병 전설이 되다",
      "gender": "male",
      "genre": "일상",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_844506761666180.jpg",
      "copy": "상세 정보 보기 2minutes_cut 페이지는 네이버 웹툰과(와) 함께합니다 광고 폐급 병사가 고기쌈 하나로 S급 에이스 떡상하는 법 #웹툰추천 #취사병전설이되다 #개그 #초능력 #웹툰 0:00 / 1:00 WEBTOON.ONELINK.ME 2min",
      "advertiser": "nwebtoon",
      "libId": "844506761666180",
      "first_seen": "2026-06-07",
      "last_seen": "2026-06-11",
      "duration_days": 5,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1429865822197004",
      "competitor": "네이버웹툰",
      "media": "meta",
      "work_title": "취사병 전설이 되다",
      "gender": "male",
      "genre": "일상",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1429865822197004.jpg",
      "copy": "상세 정보 보기 2minutes_cut 페이지는 네이버 웹툰과(와) 함께합니다 광고 개사기 취사병이 돈 쓸어담는 법 #웹툰추천 #웹툰 #취사병전설이되다 #개그 #군대썰 0:00 / 0:47 WEBTOON.ONELINK.ME 2minutes_cut 더 ",
      "advertiser": "nwebtoon",
      "libId": "1429865822197004",
      "first_seen": "2026-06-08",
      "last_seen": "2026-06-11",
      "duration_days": 4,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_2089746171886529",
      "competitor": "네이버웹툰",
      "media": "meta",
      "work_title": "취사병 전설이 되다",
      "gender": "male",
      "genre": "일상",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_2089746171886529.jpg",
      "copy": "상세 정보 보기 realfe925 페이지는 네이버 웹툰과(와) 함께합니다 광고 \"취사보조\" 인데 사단 취사점검 ㄷㄷㄷ 그의 운명은?? 선임 취사병의 갑작스러운 전출로 요리를 못 하는 신입 이병 '강성재'가 임시 취사병을 맡게 된다, 행보관의 포상 휴가",
      "advertiser": "nwebtoon",
      "libId": "2089746171886529",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_2368675400332392",
      "competitor": "네이버웹툰",
      "media": "meta",
      "work_title": "취사병 전설이 되다",
      "gender": "male",
      "genre": "일상",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_2368675400332392.jpg",
      "copy": "상세 정보 보기 2minutes_cut 페이지는 네이버 웹툰과(와) 함께합니다 광고 폐급 취사병이 만든 SSS급 오징어덮밥 #웹툰추천 #취사병전설이되다 #웹툰 #개그 #군대썰 0:00 / 0:48 WEBTOON.ONELINK.ME 2minutes_cu",
      "advertiser": "nwebtoon",
      "libId": "2368675400332392",
      "first_seen": "2026-06-07",
      "last_seen": "2026-06-11",
      "duration_days": 5,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_992546103500175",
      "competitor": "네이버웹툰",
      "media": "meta",
      "work_title": "취사병 전설이 되다",
      "gender": "male",
      "genre": "일상",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_992546103500175.jpg",
      "copy": "상세 정보 보기 2minutes_cut 페이지는 네이버 웹툰과(와) 함께합니다 광고 첫 휴가 11박 12일 나가는 미친 취사병 #웹툰추천 #웹툰 #취사병전설이되다 #개그 #군대썰 0:00 / 0:52 WEBTOON.ONELINK.ME 2minutes_",
      "advertiser": "nwebtoon",
      "libId": "992546103500175",
      "first_seen": "2026-06-07",
      "last_seen": "2026-06-11",
      "duration_days": 5,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_1318563687050014",
      "competitor": "네이버웹툰",
      "media": "meta",
      "work_title": "취사병 전설이 되다",
      "gender": "male",
      "genre": "일상",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_1318563687050014.jpg",
      "copy": "상세 정보 보기 realfe925 페이지는 네이버 웹툰과(와) 함께합니다 광고 \"취사보조\" 인데 사단 취사점검 ㄷㄷㄷ 그의 운명은?? 선임 취사병의 갑작스러운 전출로 요리를 못 하는 신입 이병 '강성재'가 임시 취사병을 맡게 된다, 행보관의 포상 휴가",
      "advertiser": "nwebtoon",
      "libId": "1318563687050014",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    },
    {
      "id": "meta_2629362850794864",
      "competitor": "네이버웹툰",
      "media": "meta",
      "work_title": "취사병 전설이 되다",
      "gender": "male",
      "genre": "일상",
      "title_conf": "정확",
      "ad_kind": "작품",
      "type": "image",
      "image": "assets/meta_2629362850794864.jpg",
      "copy": "상세 정보 보기 newyorkcitymonkeyboy 페이지는 네이버 웹툰과(와) 함께합니다 광고 웹툰 역사상 최고의 취사병 웹툰 #네이버웹툰 #취사병전설이되다 #웹툰추천 #웹툰 노출수가 적음 0:00 / 1:02 WEBTOON.ONELINK.ME n",
      "advertiser": "nwebtoon",
      "libId": "2629362850794864",
      "first_seen": "2026-06-10",
      "last_seen": "2026-06-11",
      "duration_days": 2,
      "active": true,
      "source": "meta",
      "confidence": "정확"
    }
  ]
};
